wapam

diff --git a/phpadmin b/phpadmin
--- a/phpadmin
+++ b/phpadmin
@@ -26,9 +26,25 @@ fi
 
 #	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
 #		Usage
-#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #
 
-usage="\n\n ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n  type \`phpadmin faq\` to view FAQ\n  More info @ http://code.google.com/p/termbox-phpadmin\n"
+namespace=termini
+
+usage="\n\n ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n  type \`phpadmin faq\` to view FAQ\n  More info @ http://code.google.com/p/$namespace-phpadmin\n"
+
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
+#		Errors
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #
+
+E_MISSING_VERSION_DECLARATION=1
+E_MISSING_EXTENSION_DECLARATION=2
+E_NO_SUCH_BUILT=3
+E_NO_SUCH_ACTION=4
+E_MISSING_PEAR_EXTENSION_DECLARATION=5
+
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
+#		Functions
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
 
 #	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
 #		Display default screen
@@ -36,7 +52,7 @@ usage="\n\n ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n  type \`php
 
 if [ ! "$1" ]
 then
-	echo ' phpadmin - Debian utility tool for PHP multi builts'
+	echo ' phpadmin - Debian utility tool for PHP multi builds'
 	echo -e	$usage
 	exit
 fi
@@ -65,7 +81,7 @@ then
 			then
 				echo ' Missing version declaration'
 				echo -e $usage
-				exit
+				exit $E_MISSING_VERSION_DECLARATION
 			fi
 			
 			if [ "$3" ]
@@ -154,16 +170,16 @@ then
 			then
 				echo	' <? Nothing to enable ?>'
 				echo -e $usage
-				exit
+				exit $E_MISSING_EXTENSION_DECLARATION
 			fi
 			
 			extension="$2"
 			
 			if [ ! -d "$built" ]
 			then
-				echo " <? distrib not found: $built ?>"
+				echo " <? built not found: $built ?>"
 				echo -e $usage
-				exit
+				exit $E_NO_SUCH_BUILT
 			fi
 			
 			if [ ! -d "$built"/ext/"$2" ]
@@ -199,26 +215,7 @@ then
 
 					aptitude install libmysqlclient-dev
 					
-#					if [ ! -f "$built"/bin/pecl ]
-#					then
-#						echo " <? pecl not found in: $built/bin/pecl ?>"
-#						echo -e $usage
-#						exit
-#					fi
-#					
-#					"$built"/bin/pecl install pdo_mysql
-#					
-#					echo "[phpadmin_enabled_extensions]
-#;	$extension extension for $built
-#extension=$extension.so
-#			" > "$built"/lib/conf.d/$extension.ini
-#			
-#					echo " <@ extension $extension successfully enabled in built $built @>"
-#					echo -e $usage
-#					
-#					exit
-					
-					args="--with-pdo-mysql=/usr --with-zlib-dir=/usr/lib --prefix=$built "
+					args=" $args --with-pdo-mysql=/usr --with-zlib-dir=/usr/lib"
 		
 				;;
 				
@@ -246,8 +243,6 @@ then
 				#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #
 				
 				(mbstring)
-					
-					args=" --prefix=$built"
 				
 				;;
 				
@@ -261,7 +256,19 @@ then
 					
 					aptitude install libicu-dev
 					
-					args=" --enable-intl --with-icu"
+					args=" $args --enable-intl --with-icu"
+				
+				;;
+				
+				#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
+				#		MyQLi Extension																		#
+				#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #
+				
+				(mysqli)
+					
+					aptitude install libmysqlclient-dev
+					
+					args=" $args --with-mysql=/usr"
 				
 				;;
 				
@@ -280,8 +287,7 @@ then
 			
 			
 			
-			
-			
+		
 			
 			cd "$built"/ext/"$2"
 			
@@ -393,19 +399,72 @@ extension=$extension.so
 		;;
 		
 		
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #	
+#		PEAR extension
+#	-- # -- # -- # -- # -- # -- # -- # -- # -- # -- # -- #		
 		
+		(pear:install)
 		
+			built=`pwd`
+
+			key=0
+			for k in ${myArgs[@]}
+			do
+				next=$(( $key + 1 ))
+
+				case $k in
+					(--built)	built="${myArgs[$next]}"	;;	
+					(-B)	built="${myArgs[$next]}"	;;
+				esac
+
+				key=$next
+			done
+
+
+			if [ ! "$2" ]
+			then
+				echo	' <? Nothing to install ?>'
+				echo -e $usage
+				exit $E_MISSING_PEAR_EXTENSION_DECLARATION
+			fi
+			
+			extension="$2"
+			
+			if [ ! -d "$built" ]
+			then
+				echo " <? built not found: $built ?>"
+				echo -e $usage
+				exit $E_NO_SUCH_BUILT
+			fi
+			
+			if [ ! -f "$built"/bin/pecl ]
+			then
+				echo " <? pecl not found in: $built/bin/pecl ?>"
+				echo -e $usage
+				exit
+			fi
+			
+			"$built"/bin/pecl install $extension
+			
+			echo "[phpadmin_pear_extensions]
+;	$extension extension for $built
+extension=$extension.so
+			" > "$built"/lib/conf.d/$extension.ini
+			
+			echo " <@ PEAR extension $extension successfully installed in built $built @>"
+			echo -e $usage
 		
+		;;
 		
 		
 #		Unknown action
 		
 		(*)
 		
-			echo ' Unknown action: '$1;
+			echo ' <? Unknown action: '$1' ?>';
 			echo -e $usage;
 			
-			exit;
+			exit $E_NO_SUCH_ACTION
 		
 		;;		
 		
